actions:
  1:
    action: delete_indices
    description: >-
       Delete ${INDEX} indices older than ${UNIT_COUNT:14} ${UNIT:days} (based on index name), for ${INDEX}-*
       prefixed indices. Ignore the error if the filter does not result in an
       actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: ${INDEX}-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d'
      unit: ${UNIT}
      unit_count: ${UNIT_COUNT}

  2:
    action: delete_indices
    description: >-
      Delete system indices older than ${UNIT_COUNT:14} ${UNIT:days} (based on index name), for system-*
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
    filters:
      - filtertype: pattern
        kind: prefix
        value: system-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y%m%d'
        unit: ${UNIT}
        unit_count: ${UNIT_COUNT}